# GIT HUB REPO FETCHING DATA

In [15]:
from pathlib import Path
from dotenv import load_dotenv
import os

notebook_dir = Path.cwd()  # or hardcode once you find the right folder
load_dotenv(dotenv_path=notebook_dir / ".venv/.env")

GITHUB_TOKEN = os.environ.get("GITHUB_TOKEN")
print(len(GITHUB_TOKEN) if GITHUB_TOKEN else "Token not found")

40

In [16]:
from dotenv import load_dotenv
import os
import requests
import pandas as pd

load_dotenv()  # reads .env from the current working directory and loads it into os.environ

GITHUB_TOKEN = os.environ.get("GITHUB_TOKEN")
BASE_URL = "https://api.github.com"

print(len(GITHUB_TOKEN) if GITHUB_TOKEN else "Token not found")

40

In [17]:
import os
print(os.getcwd())

c:\Users\ayush\PROJECTS\ML

In [18]:
headers = {
    "Authorization": f"token {GITHUB_TOKEN}",
    "Accept": "application/vnd.github+json"
}

response = requests.get(f"{BASE_URL}/search/repositories",
                         params={"q": "language:python", "sort": "stars", "order": "desc", "per_page": 5},
                         headers=headers)

print(response.status_code)
data = response.json()
data.keys()

200

dict_keys(['total_count', 'incomplete_results', 'items'])

In [19]:
print(data["total_count"])
print(data["incomplete_results"])

first_repo = data["items"][0]
first_repo.keys()

33110410
False

dict_keys(['id', 'node_id', 'name', 'full_name', 'private', 'owner', 'html_url', 'description', 'fork', 'url', 'forks_url', 'keys_url', 'collaborators_url', 'teams_url', 'hooks_url', 'issue_events_url', 'events_url', 'assignees_url', 'branches_url', 'tags_url', 'blobs_url', 'git_tags_url', 'git_refs_url', 'trees_url', 'statuses_url', 'languages_url', 'stargazers_url', 'contributors_url', 'subscribers_url', 'subscription_url', 'commits_url', 'git_commits_url', 'comments_url', 'issue_comment_url', 'contents_url', 'compare_url', 'merges_url', 'archive_url', 'downloads_url', 'issues_url', 'pulls_url', 'milestones_url', 'notifications_url', 'labels_url', 'releases_url', 'deployments_url', 'created_at', 'updated_at', 'pushed_at', 'git_url', 'ssh_url', 'clone_url', 'svn_url', 'homepage', 'size', 'stargazers_count', 'watchers_count', 'language', 'has_issues', 'has_projects', 'has_downloads', 'has_wiki', 'has_pages', 'has_discussions', 'forks_count', 'mirror_url', 'archived', 'disabled', 'open_issues_count', 'license', 'allow_forking', 'is_template', 'web_commit_signoff_required', 'has_pull_requests', 'pull_request_creation_policy', 'topics', 'visibility', 'forks', 'open_issues', 'watchers', 'default_branch', 'permissions', 'score'])

In [20]:
fields = {
    "name": first_repo["name"],
    "full_name": first_repo["full_name"],
    "owner": first_repo["owner"]["login"],
    "description": first_repo["description"],
    "language": first_repo["language"],
    "stargazers_count": first_repo["stargazers_count"],
    "forks_count": first_repo["forks_count"],
    "open_issues_count": first_repo["open_issues_count"],
    "watchers_count": first_repo["watchers_count"],
    "created_at": first_repo["created_at"],
    "updated_at": first_repo["updated_at"],
    "pushed_at": first_repo["pushed_at"],
    "size": first_repo["size"],
    "license": first_repo["license"]["name"] if first_repo["license"] else None,
    "topics": first_repo["topics"],
    "archived": first_repo["archived"],
}
fields

{'name': 'public-apis',
 'full_name': 'public-apis/public-apis',
 'owner': 'public-apis',
 'description': 'A collective list of free APIs',
 'language': 'Python',
 'stargazers_count': 474842,
 'forks_count': 52444,
 'open_issues_count': 1867,
 'watchers_count': 474842,
 'created_at': '2016-03-20T23:49:42Z',
 'updated_at': '2026-09-03T14:58:49Z',
 'pushed_at': '2026-09-02T02:23:53Z',
 'size': 9360,
 'license': 'MIT License',
 'topics': ['api',
  'apis',
  'dataset',
  'development',
  'free',
  'list',
  'lists',
  'open-source',
  'public',
  'public-api',
  'public-apis',
  'resources',
  'software'],
 'archived': False}

In [21]:
def extract_repo_fields(repo):
    return {
        "name": repo["name"],
        "full_name": repo["full_name"],
        "owner": repo["owner"]["login"],
        "description": repo["description"],
        "language": repo["language"],
        "stargazers_count": repo["stargazers_count"],
        "forks_count": repo["forks_count"],
        "open_issues_count": repo["open_issues_count"],
        "watchers_count": repo["watchers_count"],
        "created_at": repo["created_at"],
        "updated_at": repo["updated_at"],
        "pushed_at": repo["pushed_at"],
        "size": repo["size"],
        "license": repo["license"]["name"] if repo["license"] else None,
        "topics": repo["topics"],
        "archived": repo["archived"],
    }

rows = [extract_repo_fields(repo) for repo in data["items"]]
df = pd.DataFrame(rows)
df

,name,full_name,owner,description,language,stargazers_count,forks_count,open_issues_count,watchers_count,created_at,updated_at,pushed_at,size,license,topics,archived
0,public-apis,public-apis/public-apis,public-apis,A collective list of free APIs,Python,474842,52444,1867,474842,2016-03-20T23:49:42Z,2026-09-03T14:58:49Z,2026-09-02T02:23:53Z,9360,MIT License,"[api, apis, dataset, development, free, list, ...",False
1,free-programming-books,EbookFoundation/free-programming-books,EbookFoundation,:books: Freely available programming books,Python,395879,66732,84,395879,2013-10-11T06:50:37Z,2026-09-03T14:50:05Z,2026-09-01T09:12:19Z,21792,Creative Commons Attribution 4.0 International,"[books, education, hacktoberfest, list, resource]",False
2,system-design-primer,donnemartin/system-design-primer,donnemartin,Learn how to design large-scale systems. Prep ...,Python,367657,58209,613,367657,2017-02-26T16:15:28Z,2026-09-03T14:57:59Z,2026-03-20T01:52:19Z,11277,Other,"[design, design-patterns, design-system, devel...",False
3,awesome-python,vinta/awesome-python,vinta,"The definitive list that answers ""I want to do...",Python,317950,28629,18,317950,2014-06-27T21:00:06Z,2026-09-03T14:51:12Z,2026-09-01T08:48:12Z,6104,Other,"[awesome, awesome-list, python, python-framewo...",False
4,project-based-learning,practical-tutorials/project-based-learning,practical-tutorials,Curated list of project-based tutorials,Python,281929,36124,278,281929,2017-04-12T05:07:46Z,2026-09-03T14:44:42Z,2026-08-31T07:08:03Z,469,MIT License,"[beginner-project, cpp, golang, javascript, pr...",False

In [22]:
rows[0]

{'name': 'public-apis',
 'full_name': 'public-apis/public-apis',
 'owner': 'public-apis',
 'description': 'A collective list of free APIs',
 'language': 'Python',
 'stargazers_count': 474842,
 'forks_count': 52444,
 'open_issues_count': 1867,
 'watchers_count': 474842,
 'created_at': '2016-03-20T23:49:42Z',
 'updated_at': '2026-09-03T14:58:49Z',
 'pushed_at': '2026-09-02T02:23:53Z',
 'size': 9360,
 'license': 'MIT License',
 'topics': ['api',
  'apis',
  'dataset',
  'development',
  'free',
  'list',
  'lists',
  'open-source',
  'public',
  'public-api',
  'public-apis',
  'resources',
  'software'],
 'archived': False}

In [23]:
df.columns

Index(['name', 'full_name', 'owner', 'description', 'language',
       'stargazers_count', 'forks_count', 'open_issues_count',
       'watchers_count', 'created_at', 'updated_at', 'pushed_at', 'size',
       'license', 'topics', 'archived'],
      dtype='str')

In [24]:
def fetch_repos(query, total_repos=300, per_page=100):
    all_items = []
    pages_needed = (total_repos // per_page) + 1

    for page in range(1, pages_needed + 1):
        response = requests.get(
            f"{BASE_URL}/search/repositories",
            params={"q": query, "sort": "stars", "order": "desc",
                    "per_page": per_page, "page": page},
            headers=headers
        )
        print(f"Page {page}: status {response.status_code}")

        if response.status_code != 200:
            print("Stopping due to error:", response.json())
            break

        page_data = response.json()
        all_items.extend(page_data["items"])

        if len(page_data["items"]) < per_page:
            break  # reached the last available page

    return all_items[:total_repos]

repo_items = fetch_repos("language:python", total_repos=300)
len(repo_items)

Page 1: status 200
Page 2: status 200
Page 3: status 200
Page 4: status 200

300

In [25]:
rows = [extract_repo_fields(repo) for repo in repo_items]
df = pd.DataFrame(rows)
print(df.shape)
df.head()

(300, 16)

,name,full_name,owner,description,language,stargazers_count,forks_count,open_issues_count,watchers_count,created_at,updated_at,pushed_at,size,license,topics,archived
0,public-apis,public-apis/public-apis,public-apis,A collective list of free APIs,Python,474842,52444,1867,474842,2016-03-20T23:49:42Z,2026-09-03T14:58:49Z,2026-09-02T02:23:53Z,9360,MIT License,"[api, apis, dataset, development, free, list, ...",False
1,free-programming-books,EbookFoundation/free-programming-books,EbookFoundation,:books: Freely available programming books,Python,395879,66732,84,395879,2013-10-11T06:50:37Z,2026-09-03T14:50:05Z,2026-09-01T09:12:19Z,21792,Creative Commons Attribution 4.0 International,"[books, education, hacktoberfest, list, resource]",False
2,system-design-primer,donnemartin/system-design-primer,donnemartin,Learn how to design large-scale systems. Prep ...,Python,367658,58209,613,367658,2017-02-26T16:15:28Z,2026-09-03T15:00:24Z,2026-03-20T01:52:19Z,11277,Other,"[design, design-patterns, design-system, devel...",False
3,awesome-python,vinta/awesome-python,vinta,"The definitive list that answers ""I want to do...",Python,317951,28629,18,317951,2014-06-27T21:00:06Z,2026-09-03T15:02:06Z,2026-09-01T08:48:12Z,6104,Other,"[awesome, awesome-list, python, python-framewo...",False
4,project-based-learning,practical-tutorials/project-based-learning,practical-tutorials,Curated list of project-based tutorials,Python,281929,36124,278,281929,2017-04-12T05:07:46Z,2026-09-03T14:44:42Z,2026-08-31T07:08:03Z,469,MIT License,"[beginner-project, cpp, golang, javascript, pr...",False

In [26]:
df.isna().sum()

name                  0
full_name             0
owner                 0
description           4
language              0
stargazers_count      0
forks_count           0
open_issues_count     0
watchers_count        0
created_at            0
updated_at            0
pushed_at             0
size                  0
license              18
topics                0
archived              0
dtype: int64

In [27]:
df.dtypes

name                    str
full_name               str
owner                   str
description             str
language                str
stargazers_count      int64
forks_count           int64
open_issues_count     int64
watchers_count        int64
created_at              str
updated_at              str
pushed_at               str
size                  int64
license                 str
topics               object
archived               bool
dtype: object